---
name: cron
on:
  push:
  schedule:
  - cron: '0 * * * *'
permissions: "write-all"
jobs:
  guix:
    runs-on: "ubuntu-latest"
    steps:
      - name: "[cron-mirror|guix] checkout"
        uses: "actions/checkout@v4"
        with:
          fetch-depth: 0
      - name: "[cron-mirror|guix] configure git"
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
      - name: "[cron-mirror|guix] clone"
        run: |
          git clone --mirror https://git.savannah.gnu.org/git/guix.git
      - name: "[cron-mirror|guix] push"
        run: |
          cd guix.git
          git push --mirror
...
