---
name: cron
on:
  push:
  schedule:
  - cron: '0 * * * *'
permissions: "write-all"
jobs:
  guix:
    runs-on: "ubuntu-latest"
    steps:
      - name: "[cron-mirror|guix] checkout"
        uses: "actions/checkout@v4"
        with:
          fetch-depth: 0
      - name: "[cron-mirror|guix] configure git"
        run: |
          echo CURRENT_REPO="https://${GITHUB_ACTOR}:${{ sercrets.GITHUB_TOKEN }}@github.com/${GITHUB_REPOSITORY}.git" >> ${GITHUB_ENV}
          git config user.name ${GITHUB_ACTOR}
          git config user.email ${GITHUB_ACTOR}@github.com
      - name: "[cron-mirror|guix] clone"
        run: |
          git clone --mirror https://git.savannah.gnu.org/git/guix.git
      - name: "[cron-mirror|guix] push"
        run: |
          cd guix.git
          git push --mirror ${CURRENT_REPO}
...
